### ISSUE TITLE
Enum column override issue

### ISSUE THREAD

**Issue by RtypeStudios** [christophano/Effort.Extra#11]
Hi Chris, 

Great extra add on, I'd love to see this merged into Effort itself!

We have hit a bug and after a fair amount of digging. it appears that enum properties with the column attribute are being ignored.

If the column is configured like so:
```csharp
        [Column("testfieldId")]
        public LogAction TestField { get; set; }
```
The data loader throws the following error:

 Effort.Exceptions.EffortException: Effort.Exceptions.EffortException: Unhandled exception while trying to initialize the content of 'Table<dbo_Users>' table ---> Effort.Exceptions.EffortException: An unhandled exception occurred while trying to assign value '[null]' to Property'System.Int32' of type 'testfieldId' during entity initialization for table 'Effort.Internal.DbManagement.Schema.TableName' ---> System.NullReferenceException: Object reference not set to an instance of an object..

but if the column is changed to:
```csharp
        [Column("testfieldId")]
        public int TestField { get; set; }
```
Everything works correctly, so for some reason if the property is an Enum type it appears extra isn't loading the column attribute definition.

Additionally we use fluent configuration to setup our entities, by the looks of things extra doesn't read the metadata from the context so fluent isn't supported?

I'm happy to take a look at the enum issue and fix it myself then submit a pull request, but I had a trouble getting the testing framework to run in VS. Any tips on what i need to install to be able to run those tests? I have resharper if that helps.

Thanks!
Alex

**Comment by christophano** [comment]
Hi Alex,
I'll take a look at this as soon as I get a moment.

With regards to the unit tests, they're written using Machine Specifications - there was a runner for ReSharper (which is what I used - not sure if it's updated though) and there is also a console runner. I imagine there's a visual studio runner too.

With regards to reading the configuration, this is passed into the `ITableDataLoaderFactory` implementation, so the real work is done in the effort library itself.

**Comment by RtypeStudios** [comment]
Hi Chris,

Great thank you. I will take a look into getting the tests running. I tried
the R# one but I had trouble getting it to work.

Ahh okay, I missed that. thanks for the reply.

**Comment by christophano** [comment]
The issue isn't exactly related to it being an `enum`, it's because the `ColumnDescriptor` type (`int` in this case) did not exactly match the property type. Of course, that's a perfectly acceptable (and expected) scenario, so I removed the type check.

**Comment by christophano** [comment]
Uploaded to nuget as version 1.4

**Comment by RtypeStudios** [comment]
Awesome, thank you Chris.
