### ISSUE TITLE
Example with ef?

### ISSUE THREAD

**Issue by JoeShmoel** [christophano/Effort.Extra#14]
Hi,
I can not get the cached loader to work from the entities. I have posted my example code below. It is just a single context, with a single class it doesnt populate the context even with a single entity.

```csharp
[TestClass]
public class SimpleTest
{
    public class MyClass
    {
        public Guid Id { get; set; } = Guid.NewGuid();
    }
    public class simpeContext : DbContext, IsimpeContext
    {
        public simpeContext(DbConnection connection) : base(connection, true) {}
        public simpeContext(string connectionString) : base(connectionString) { }
        public virtual DbSet<MyClass> MyClass { get; set; } 
    }
    [TestInitialize]
    public void Init()
    {
        ObjectData nhhData = new ObjectData();

        DbConnection connection2;
        ObjectDataLoader nhhObjectDataLoader;

        nhhData.Table<MyClass>().Add(new MyClass());
        ObjectDataLoader = new ObjectDataLoader(nhhData);
        connection2 = DbConnectionFactory.CreateTransient(new ObjectDataLoader(nhhData));
        var simpeContext2 = new simpeContext(connection2);
        var f = simpeContext2.MyClass.First();
    }
}
```
Thank you for any help.

**Comment by christophano** [comment]
Hi Joe,
sorry for the delay - I don't actually use `Effort` in my own work anymore, so I don't monitor this repo very much.
Your example looks mostly okay, you just need to change the `TableNamingStrategy` on the instance of `ObjectData`.
Entity Framework defaults to pluralising table names, so if you create it like this; `ObjectData nhhData = new ObjectData(TableNamingStrategy.Pluralised);` then your example works.

Hope this sorts your issue, but feel free to re-open this if there's anything else.

Chris
