### ISSUE TITLE
Merge Effort.Extra into Effort

### ISSUE THREAD

**Issue by JonathanMagnan** [christophano/Effort.Extra#16]
Hello Chris,

I’m the owner of Effort (since the end of 2017).

Do you mind if we merge Effort.Extra into Effort? I will add some copyright about you but I'm asking in case something doesn't follow Apache 2.x.

Btw, thank a lot for this library 😉

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by christophano** [comment]
Hi Jonathan,
I'm more than happy for you to merge this into the core library.
Let me know if you need any help.

Chris

**Comment by arden828** [comment]
@JonathanMagnan @christophano 

This library works really well for me, any plan to go ahead with the merge?

**Comment by JonathanMagnan** [comment]
Hello @arden828 ,

My bad, I thought we already answered here.

The code has already been merged starting from version 2.x of `Effort`.

Best Regards,

Jonathan
