### ISSUE TITLE
Library has no strong name - not signed.

### ISSUE THREAD

**Issue by voroninp** [christophano/Effort.Extra#2]
Hello, thanks for the great extension.

We sign our application libraries, but test libraries need to be signed as their names set in InternalsVisibleTo attribute. As a consequence, compiler requires Effort.Extra to have strong name as well.

**Comment by christophano** [comment]
Strongly named versions added and uploaded to nuget.
[Extra Effort](https://www.nuget.org/packages/Effort.Extra.StrongName/1.2.3)
[Extra Effort for EF6](https://www.nuget.org/packages/Effort.Extra.EF6.StrongName/1.2.3)

**Comment by voroninp** [comment]
Thanks
