### ISSUE TITLE
Strongly named version of Effort.Extra is probably not rewriten with CodeContracts

### ISSUE THREAD

**Issue by voroninp** [christophano/Effort.Extra#3]
Exception is thrown at run time:

[Window Title]
vstest.executionengine.x86.exe - Precondition failed.

[Main Instruction]
vstest.executionengine.x86.exe - Precondition failed.

[Content]
Description: An assembly (probably "Effort.Extra.EF6") must be rewritten using the code contracts binary rewriter (CCRewrite) because it is calling Contract.Requires<TException> and the CONTRACTS_FULL symbol is defined.  Remove any explicit definitions of the CONTRACTS_FULL symbol from your project and rebuild.  CCRewrite can be downloaded from http://go.microsoft.com/fwlink/?LinkID=169180. 
After the rewriter is installed, it can be enabled in Visual Studio from the project's Properties page on the Code Contracts pane.  Ensure that "Perform Runtime Contract Checking" is enabled, which will define CONTRACTS_FULL.

[Expanded Information]
Stack Trace:
   at System.Diagnostics.Contracts.Contract.AssertMustUseRewriter(ContractFailureKind kind, String contractKind)
   at System.Diagnostics.Contracts.Contract.Requires[TException](Boolean condition)
   at Effort.Extra.ObjectDataLoader..ctor(ObjectData data) in c:\Users\Christopher\Documents\GitHub\Effort.Extra\Effort.Extra\ObjectDataLoader.cs:line 18
   at

**Comment by christophano** [comment]
Very careless of me; I've enabled the rewriter for the signed versions now.
