### ISSUE TITLE
Strong name validation failed

### ISSUE THREAD

**Issue by voroninp** [christophano/Effort.Extra#4]
After a while I returned to Extra and got the excpetion:

System.IO.FileLoadException: Could not load file or assembly 'Effort.Extra, Version=1.2.4.0, Culture=neutral, PublicKeyToken=d5e6d8dafe415d10' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A).

SN tool says: Effort.Extra.dll is a delay-signed or test-signed assembly

So assembly has a strong name but is not actually signed =)

**Comment by christophano** [comment]
Can you take a look at the latest build?
I was previously setting the key using the `AssemblyKeyFile` attribute, but saw some warnings related to this in the build output, so I've set it using the `csproj` settings.
