### ISSUE TITLE
Probably a bug in ObjectTableDataLoader<T>.CreateFormatter()

### ISSUE THREAD

**Issue by voroninp** [christophano/Effort.Extra#5]
``` csharp
protected Func<T, object[]> CreateFormatter()
{
    var type = typeof(T);
    var param = Expression.Parameter(type, "x");
    var initialisers = table.Columns
        .Select(c => Expression.TypeAs(Expression.Property(param, type.GetProperty(c.Name)), typeof(object)));
    var newArray = Expression.NewArrayInit(typeof(object), initialisers);
    return Expression.Lambda<Func<T, object[]>>(newArray, param).Compile();
}
```

`type.GetProperty(c.Name)` returns `null` when property is marked with `Column` attribute - it simply looks for wrongly named property. Actually, I could not find the exact place where Effort converts properties' names to column names, but debugging shows that it does. So there's a need for reverse mapping from column to entity's property name.

**Comment by christophano** [comment]
Good spot, I was handling only the simple use case I required, but of course custom column names will be common. Thanks!
