### ISSUE TITLE
CreateFormatter fails for Columns without Properties

### ISSUE THREAD

**Issue by user378230** [christophano/Effort.Extra#6]
I'm using Database-First edmx, I have a column defined in the table store but not as a property on the entity, which is causing an exception to be thrown when attempting to use the DbContext.

With reference to the following:

``` c#
protected Func<T, object[]> CreateFormatter()
{
    var type = typeof(T);
    var param = Expression.Parameter(type, "x");
    var initialisers = table.Columns
        .Select(c => Expression.TypeAs(Expression.Property(param, GetProperty(type, c)), typeof(object)));
    var newArray = Expression.NewArrayInit(typeof(object), initialisers);
    return Expression.Lambda<Func<T, object[]>>(newArray, param).Compile();
}
```

The column appears in `table.Columns` but obviously the does not have an appropriate property, so `GetProperty(...)` returns `null` this throws an Exception in `Expression.Property` (parameter property cannot be null). 

To work around this I did the following

``` c#
protected Func<T, object[]> CreateFormatter()
{
    var type = typeof(T);
    var param = Expression.Parameter(type, "x");
    var initialisers = table.Columns
        .Select(c => GetProperty(type, c))
        .Select(prop => (prop == null ? (Expression)Expression.Constant(null) : (Expression)Expression.TypeAs(Expression.Property(param, prop), typeof(object))));
    var newArray = Expression.NewArrayInit(typeof(object), initialisers);
    return Expression.Lambda<Func<T, object[]>>(newArray, param).Compile();
}
```

to return null as the value for that column in `GetData(...)`. 

> _In my use case the column is a calculated column in SQL Server which I'm using to feed a navigation property, the actual value is irrelevant to me and since it is read only I don't want to make a property for it._

I can use my own version but it would be nice to use the official version. If you need any additional information, I'd be happy to assist. 

> _p.s. Thanks for making this package it was exactly what I was looking for!_

**Comment by christophano** [comment]
Thanks for the feedback! This was a case I'd briefly thought about previously, but didn't fit my known requirements.
I think it would probably be best to just filter out the properties that don't exist on the object, rather than the ternary expression to return null where it doesn't exist.
I'll have to test this to make sure it won't cause further problems with Effort itself.
