### ISSUE TITLE
Pluralization doesn't work

### ISSUE THREAD

**Issue by NameOfTheDragon** [christophano/Effort.Extra#7]
Please consider this a feature request.

When specifying a table,
`data.Table<Category>.Add(new Category());`

it is unfortunate that Effort.Extra does not pluralize `Category` to `Categories` as the Entity Framework code-first would do by default. This leads to a lot of extra effort (ha!) specifying table names because the entity class names don't match the pluralized database table names that EF Code First creates.

It would be really handy if Effort.Extra followed the same pluralization conventions as EF.

**Comment by NameOfTheDragon** [comment]
Never mind - I'm just being dumb. I didn't realize that I could specify the table naming strategy when creating the ObjectData instance.

**Comment by christophano** [comment]
No problem, glad to see you figured it out.
I really ought to update the read me, as it doesn't mention the naming strategy work at all, so thanks for pointing this out!
