### ISSUE TITLE
Support for inheritance (table per hierarchy)

### ISSUE THREAD

**Issue by meinsiedler** [christophano/Effort.Extra#8]
Hi,

first of all: Thanks for this great extension. It's really very useful.

However, I do have a question regarding inheritance of entities. It seems like this is currently not supported by Effort.Extra. Is this correct? At least, I couldn't get it to work.

To clarify, let's say I have the following entities:

``` csharp
public abstract class Vehicle
{
  [Key]
  [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
  public int Id { get; set; }
  public string Name { get; set; }
}

public class Car : Vehicle
{
  public int Power { get; set; }
}

public class Plane : Vehicle
{
  public int MaxPayload { get; set; }
}
```

And a DBContext like this:

``` csharp
public class MyContext : DbContext
{
  // ctor, etc.
  IDbSet<Vehicle> Vehicles { get; set; }
}
```

I tried to set up the `ObjectData` instance like the following, but when querying the Vehicles, I never get any results. The Vehicles-DbSet is always empty.

``` csharp
var data = new ObjectData(TableNamingStrategy.Pluralised);
data.Table<Vehicle>().Add(new Car { Id = 1, Name = "Volkswagen Beetle", Power = 34 });
data.Table<Vehicle>().Add(new Car { Id = 2, Name = "Citroen 2CV", Power = 22 });
```

I also tried to use Effort's `CsvDataLoader` with the following CSV-File. With the `CsvDataLoader` the inheritance works as expected and I get the results from the Vehicles-DbSet.

```
Id,Name,Power,MaxPayload,Discriminator
1,"Volkswagen Beetle",34,,"Car"
2,"Citroen 2CV",28,,"Car"
3,"Airbus A380",,66400,"Plane"
```

I created a simple demo project with some unit tests to show what's going on: https://github.com/meinsiedler/Effort-InheritanceDemo

One test in the project, namely the one which asserts the Vehicles-DbSet which was set up with the `ObjectDataLoader` fails because of the above stated reasons.

It would be really great if,
1. You could clarify if I'm correct on the current behavior of Effort.Extra regarding inheritance or if I'm completly on the false path and I did something wrong.
2. You could look into the issue and see if inheritance can be supported by Effort.Extra. I'm also willing to help you implementing this feature if desired.

**Comment by christophano** [comment]
This is a great question! Table per hierarchy is something I've overlooked/disregarded, mostly as I don't use it much myself!
I've taken a look at your example project (thanks for that, it demonstrated the problem perfectly) and have completed a _rough_ first pass to include this scenario.
There are 2 problems here.
1. Creating a `get property` expression when the property does not exist on the base type.  
   I'm currently utilising `Binder.GetMember` (wrapped in a `try... catch`) to get the members as if the object was a dynamic type. It works, but it's kludgy, and I'd like to do away with the `try... catch` if possible.
2. Providing the `Discriminator` column.  
   This is (and correct me if I'm wrong), _by convention_, just the class name, so is an easy fix.

**Comment by meinsiedler** [comment]
Thank you for your really fast response (even with some new code already!).

To your two problems:
1. I'm not totally into your code, but why exactly do you need the `try... catch`? Shouldn't the binding work anyway? And in case it does not (what would cause the binding not to work?) shouldn't it be better to throw the `RuntimeBinderException` instead of silently failing by swallowing the exception?
2. You're right, the value for the `Discriminator` column is the class name, but just by _convention_ as you correctly noted. This means that it's also possible that this value can be customized. (I personally never customized this value but rather always used the convention.)

While testing the inheritance of Effort.Extra and while I created the demo I came up with something like this to provide the `Discriminator` column (I thought it might work if I provided the column):

``` csharp
class EffortCar : Car
{
  public string Discriminator { get; } = "Car";
}

class EffortPlane : Plane
{
  public string Discriminator { get; } = "Plane";
}
```

This is by far not an ideal solution but would solve the providing of the Discriminator columns.

Another approach I thought about was to provide a new method on the `ObjectData` object with something roughtly like this (just to get the idea):

``` csharp
var data = new ObjectData();
data.AddDiscriminator<Car>(); // use class name as default discriminator value
data.AddDiscriminator<Plane>("P"); // optionally provide other values instead of class name
```

**Comment by christophano** [comment]
The try catch is because a `RuntimeBinderException` will be thrown if a property does not exist (for example, `MaxPayload` on a car). I haven't (yet) come up with a satisfactory way to check if the property exists _before_ trying to access it (without using reflection for each and every object), but I'll persevere.

The idea of being able to specify metadata appeals to me. The `Table` method returns an `IList<>` for simplicity, but I've considered having a custom type. `Add` is the only `IList<>` method that is important in any case.

**Comment by meinsiedler** [comment]
I think I miss something here. Can you add a test which shows how this works? As far as I can see (and please correct me if I'm wrong) the generic `T` in `ObjectTableDataLoader` is always the type of the table, i.e. the base type (e.g. `Vehicle`), so `table.Columns` in the `CreateFormatter` method will only return the columns of the base type.

I like the idea of returning a custom type from the `Table` method. This would even be better than adding a method to the `ObjectData` object itself, so the table-specific metadata is better coupled.

PS: Note that you broke the build with your latest commit, see https://ci.appveyor.com/project/christophano/effort-extra/build/messages

**Comment by christophano** [comment]
Sorry this took so long, but version 1.3 adds support for user specified discriminators.
Default column name is "Discriminator" and default value is the derived type name.
`ObjectData.Table<T>()` now returns an `ObjectDataTable<T>` (which implements `IList<T>` for backwards compatibility).
You can set the name of the discriminator column by setting the `DiscriminatorColumn` property (default is "Discriminator") and can set the discriminator value for each derived type by calling the `AddDiscriminator<TType>(string)` method (default is `typeof(TType).Name`).

**Comment by meinsiedler** [comment]
This is great news!
Thank you for supporting this feature. The inheritance works like a charm now. :-)
