### ISSUE TITLE
Many-to-Many relationships don't appear to initialize correctly

### ISSUE THREAD

**Issue by NameOfTheDragon** [christophano/Effort.Extra#9]
I'm trying to initialise some data that has a many-to-many relationship, ApplicationUser >-< Badge.
I'm doing it along the lines of the code below. However, when the user entity is retrieved later, it has no badges and vice versa.

```
        public ControllerContextBuilder<TController> WithUserAwardedBadges(string userId, string userName, params int[] badges)
            {
            var user = new ApplicationUser
                {Id = userId, UserName = userName, Email = $"{userId}@nowhere.nw", EmailConfirmed = true};
            foreach (var badgeId in badges)
                {
                var badgeToAdd = new Badge
                    {
                    Id = badgeId,
                    Name = $"Badge-{badgeId}",
                    ImageIdentifier = $"Badge-{badgeId}"
                    };
                user.Badges.Add(badgeToAdd);
                badgeToAdd.Users.Add(user);
                data.Table<Badge>().Add(badgeToAdd);
                }
            data.Table<ApplicationUser>("AspNetUsers").Add(user);

            return this;
            }
```

Is this maybe a side-effect of ASP.Net Identity not using the normal table naming conventions? It occurs to me that from the perspective of the `Badge` entity, there's no way for it to figure out the table name for the `ApplicationUser` entity. Is there perhaps some configuration trick for this case that I've missed?

**Comment by christophano** [comment]
Hi there,
I'll take a look at this request as soon as I can.

**Comment by christophano** [comment]
Okay, the way I've done this in the past when I've had generated classes representing the joins is to add the join types manually.

Example:
You have a type called Student which has many Courses and a type called Course which has many students. It may be that Entity Framework has generated the join type for you, so you have a type called (for example) StudentCourses or CourseStudents, in which case, just add these objects to a table of their own in the same way as you're adding the entities that they join.
If (and I hope this is the case - join entities are just nasty) you don't have generated entities representing a join, you can just create one.
Create a class in your test project which represents the join, with the correct names, and add them as above.
From your library under test:

``` c#
public class Student
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Course> Courses { get; set; }
}
public class Course
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Student> Students { get; set; }
}
```

In your test project:

``` c#
public class StudentCourse
{
    public int Id { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
}
...
var data = new ObjectData();

var students = data.Table<Student>()
students.Add(new Student { Id = 1, Name = "John" });
students.Add(new Student { Id = 2, Name = "Jeff" });

var courses = data.Table<Course>();
courses.Add(new Course { Id = 1, Name = "C#" });
courses.Add(new Course { Id = 1, Name = "F#" });

var studentCourses = data.Table<StudentCourse>();
studentCourses.Add(new StudentCourse { Id = 1, StudentId = 1, CourseId = 1 });
studentCourses.Add(new StudentCourse { Id = 2, StudentId = 1, CourseId = 2 });
studentCourses.Add(new StudentCourse { Id = 3, StudentId = 2, CourseId = 1 });
studentCourses.Add(new StudentCourse { Id = 4, StudentId = 2, CourseId = 2 });
```

should give us 2 students, each with 2 courses.

Sorry this has taken so long - this is probably not a lot of use to you anymore!
